// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzayebskbaqeggputbdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YXllYnNrYmFxZWdncHV0YmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5Nzc4MTksImV4cCI6MjA3MjU1MzgxOX0.xlFijz6DZIl1u1FZlLkb1u7_ozWj9es-AXF2--zTst0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});